version: '3.8'

services:
  web:
    build: .
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/logistics_db
      - SECRET_KEY=your-secret-key-here
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - logistics-network

  db:
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=logistics_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - logistics-network

volumes:
  postgres_data:

networks:
  logistics-network:
    driver: bridge 