"""add insurance_type_id to order model

Revision ID: 2b4ca9ef8414
Revises: 2caeeec59069
Create Date: 2025-05-21 05:03:19.372413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b4ca9ef8414'
down_revision = '2caeeec59069'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('insurance_type_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'insurance_types', ['insurance_type_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('insurance_type_id')

    # ### end Alembic commands ###
