"""add pickup_point_id to order model

Revision ID: 3caeefc59069
Revises: 2caeeec59069
Create Date: 2025-05-21 06:15:00.000000

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime

# revision identifiers, used by Alembic.
revision = '3caeefc59069'
down_revision = '2caeeec59069'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pickup_point_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_order_pickup_point', 'pickup_points', ['pickup_point_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('fk_order_pickup_point', type_='foreignkey')
        batch_op.drop_column('pickup_point_id')
    # ### end Alembic commands ### 